pipeline { 
    agent any

    stages{ 
            stage("checkout code"){
                steps{
                       checkout scm}
            }

    stage("Build"){
          steps{
               bat "mvn clean install -Dmaven.test.skip=true"
          }

    }

    stage("Archive Artifact"){
        steps{
        archiveArtifacts artifacts:"target/*.war"
        }
    }

     stage("deployment"){
         steps{

        deploy adapters: [tomcat9(url: http://3.111.217.149:8080/',
                                  credentialsId: "TomcatCreds")],
            war: "target/*.war",
            contextPath: "app"

         }

     }
        stage("Notification"){
            steps{
                emailext(
                    subject: "Job Completed",
                    body: "Jenkins pipeline job for maven  build job completed",
                    to: "simbathecat657@gmail.com"
                    )
            }
        }
