pipeline {
    agent any

    environment {
        TOMCAT_CREDENTIALS = credentials('tomcat-tomcat') // Replace 'tomcat-credentials-id' with your credentials ID
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/simba657/simple-java-maven-app.git', branch: 'main' // Replace with your Git repository URL
            }
        }
        stage('Build') {
            steps {
                // Assuming you're using Maven for build
                sh 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                script {
                    def warFile = 'target/your-app.war' // Replace with the path to your WAR file
                    deploy adapters: [tomcat9(credentialsId: 'tomcat-credentials-id', path: '', url: 'http://http://3.111.217.149:8080/manager/html')], contextPath: '/your-app', war: warFile
                }
            }
        }
    }

    post {
        success {
            echo 'CI/CD Pipeline job successfully built and deployed the application on the server.'
        }
        failure {
            echo 'CI/CD Pipeline job failed.'
        }
    }
}
